import { StyleSheet } from "react-native";
import { colors } from "@/config";

export const styles = StyleSheet.create({
  stack: {
    gap: 8,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  stepLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 8,
    marginBottom: 4,
  },
  multiLegHint: {
    color: colors.muted,
    fontSize: 14,
    marginTop: 8,
    marginBottom: 4,
    lineHeight: 20,
  },
  multiLegHintActive: {
    color: colors.text,
    backgroundColor: colors.accentMuted,
    borderColor: colors.accent,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  fixtureRule: {
    color: colors.muted,
    fontSize: 12,
    marginBottom: 4,
  },
  groupLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "500",
    marginTop: 4,
    marginBottom: 4,
  },
  selectedMarket: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.4)",
    backgroundColor: "rgba(20, 83, 45, 0.2)",
    borderRadius: 10,
    padding: 12,
  },
  selectedMarketCopy: { flex: 1 },
  selectedMarketEyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  selectedMarketLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    marginTop: 4,
  },
  changeMarket: { color: colors.accent, fontSize: 13, fontWeight: "600" },
  pressed: { opacity: 0.75 },
  meta: {
    color: colors.muted,
    fontSize: 14,
  },
  oddsCompareCard: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 10,
    gap: 6,
  },
  oddsCompareRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  oddsCompareName: {
    color: colors.text,
    fontSize: 13,
    flexShrink: 1,
  },
  oddsCompareValue: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  oddsCompareOdds: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "600",
  },
  warnText: {
    color: colors.warning,
    fontSize: 13,
    marginTop: 4,
  },
  banner: {
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.3)",
    backgroundColor: "rgba(20, 83, 45, 0.4)",
    borderRadius: 10,
    padding: 12,
  },
  bannerText: {
    color: colors.accent,
    fontSize: 14,
  },
  bannerHint: {
    color: colors.accent,
    fontSize: 12,
    marginTop: 4,
    opacity: 0.85,
  },
  memberRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 12,
  },
  memberName: {
    color: colors.text,
    fontSize: 14,
  },
  submitted: {
    color: colors.accent,
    fontSize: 14,
  },
  legCard: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 12,
  },
  legHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  legHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
  },
  legUser: {
    color: colors.text,
    fontWeight: "600",
    fontSize: 14,
    flex: 1,
  },
  legPick: {
    color: colors.muted,
    fontSize: 14,
    marginTop: 4,
  },
  odds: {
    color: colors.accent,
    fontWeight: "600",
    fontSize: 14,
  },
  outcomeBadge: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  outcomeText: {
    fontSize: 11,
    fontWeight: "600",
  },
  openLink: {
    marginTop: 8,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.5)",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  openLinkText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "600",
  },
  accaCard: {
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.3)",
    backgroundColor: "rgba(20, 83, 45, 0.2)",
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  accaMain: {
    gap: 4,
  },
  accaLabel: {
    color: colors.text,
    fontWeight: "600",
    fontSize: 14,
  },
  accaOdds: {
    color: colors.accent,
    fontSize: 28,
    fontWeight: "700",
  },
  compareHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  showBookmakersButton: {
    alignItems: "center",
    borderRadius: 8,
    marginTop: 6,
    paddingVertical: 10,
  },
  showBookmakersText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "600",
  },
  lockedAtRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  logoImage: {
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  logoFallback: {
    borderRadius: 6,
    backgroundColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  logoFallbackText: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: "700",
  },
  rankRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginTop: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "transparent",
    gap: 8,
  },
  rankRow1: {
    borderColor: "rgba(34, 197, 94, 0.55)",
    backgroundColor: "rgba(20, 83, 45, 0.45)",
  },
  rankRow2: {
    borderColor: "rgba(148, 163, 184, 0.5)",
    backgroundColor: "rgba(100, 116, 139, 0.2)",
  },
  rankRow3: {
    borderColor: "rgba(217, 119, 6, 0.45)",
    backgroundColor: "rgba(180, 83, 9, 0.18)",
  },
  rankLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  rankRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  rankBadge: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    backgroundColor: colors.border,
  },
  rankBadge1: {
    backgroundColor: colors.accent,
  },
  rankBadge2: {
    backgroundColor: "#cbd5e1",
  },
  rankBadge3: {
    backgroundColor: "#d97706",
  },
  rankBadgeText: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  rankBadgeTextDark: {
    color: "#000",
  },
  rankNameCol: {
    flex: 1,
    minWidth: 0,
  },
  rankName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "500",
  },
  rankName1: {
    fontSize: 15,
    fontWeight: "700",
  },
  rankNamePodium: {
    fontWeight: "600",
  },
  rankOdds1: {
    color: colors.accent,
    fontSize: 18,
    fontWeight: "700",
  },
  rankOddsPodium: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
  },
  settleLeg: {
    marginTop: 12,
    gap: 8,
  },
  outcomePicker: {
    flexDirection: "row",
    gap: 8,
  },
  outcomeOption: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  outcomeOptionSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  outcomeOptionText: {
    color: colors.muted,
    fontSize: 13,
    textTransform: "capitalize",
  },
  outcomeOptionTextSelected: {
    color: colors.accent,
    fontWeight: "600",
  },
  leaderboardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 12,
  },
  historyCard: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 12,
    gap: 8,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  historyTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  viewAll: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "500",
  },
  historyLeg: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    paddingTop: 8,
    gap: 2,
  },
});
