-- AlterTable
ALTER TABLE "Leg" ALTER COLUMN "pointsAwarded" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GroupMember" ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "totalPoints" SET DATA TYPE DOUBLE PRECISION;
